language: node_js
node_js:
- 0.1
deploy:
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: MaGrmlXv7GSY3jfK2/iD/YtcIMrbR6IZF5uUFSzCrXYPOyC/RZ+/P1joEVLZlVsxGX4nrMomlhml7E3bJyWaylyxZgqMXgGBLf1UtuTSpzYwgAuH9agrsEUa7hd0w4j6+kczBZFZW6zy0IP6sn3XhBgp71Z2CLjEn5s8a6bkAuiLWwvrpGPqM64DHI9aY0QO4eiaN0uiJDQSIPukYgLfWCjDLYQVagT10ZGNVQ1WSaNUN3vI1ttZIrBv33uoTZlcdVU2nvLu5jyl2//LTLnuGHT3DYS5TarwBUeMCfWmFdUeTXtl0wKLjuyCHcUzG69VttAOSonfrLTM+kB7E8+95HL7klb4hkAWpoHXsnD2h3bzoulKRxHBhehItRkCRaeaQAU6hgr+zZUrbKLL2mO0ofjvv29+4LXjyBM3VEB4O8MTvzBkOaL4bmzjzOptRD0/eb6lJMlF4q+WzsQvh8VEGgEreaYEJPZ6WYqGpgubfuohiVbesMDxT2IRJvaTQLpj259YoJBKJs9sP0tNVuIIabanIH7097mG4/Ci2LvoQmzrUYYTKH5l1BZHiRJ6Gjf1ELfR9g7+9h/emwa1YitrKYGnDxw6sbyTIe02cXlSoq5wSl2apFVgMaE5MSOp1XMHS1xgt44FdTPF7Zi23yyDMax7Cj+geyQiT78ZUGK7fxQ=
  app: nodejs-heroku-test
  on:
    repo: onlineth/node-js-getting-started
